### ISSUE TITLE
tex export fails to compile with negative sign

### ISSUE THREAD

**Issue by ExarchD** [AlecAivazis/feynman#86]
It seems that negative signs are not friendly in the latex export for labelDistance and labelLocation:
```
\begin{feynman} 
    \gluon[label=$g$, labelDistance=-0.30, labelLocation=1.20]{2.20, 2.20}{0.20, 4.20}
    \gluon[label=$g$, labelDistance=0.60, labelLocation=-0.10]{0.20, 0.20}{2.20, 2.20}
    \gluon[color=000000, label=$g$]{2.20, 2.20}{5.20, 2.20}
    \fermion[label=$\anti{t}$, labelDistance=0.00, labelLocation=-0.14]{7.20, 4.20}{5.20, 2.20}
    \fermion[label=$t$, showArrow=true, flip=false, labelDistance=0.30, labelLocation=1.00]{5.20, 2.20}{7.20, 0.20}
\end{feynman}
```

Adding parentheses around the negative values fixed the problem for me.

**Comment by ExarchD** [comment]
Sorry I guess I was hasty. There are a few issues I hit with this code, and I don't think its the negative sign. Here's the error it outputs:

```
!FP error: UPN stack is empty!.
\FP@errmessage #1->\errmessage {FP error: #1!}                                                                                                                                                                                                  l.15 ...abelLocation=1.20]{2.20, 2.20}{0.20, 4.20}
```

**Comment by AlecAivazis** [comment]
hey @ExarchD - thanks for submitting the issue! If adding parentheses fixes the problem, then I think the issue **is** in fact with the minus sign. I can submit a fix that wraps the exported values in parentheses if so.

**Comment by AlecAivazis** [comment]
After browsing a bit online, it seems like a few people have run into this issue when using FPEval

**Comment by AlecAivazis** [comment]
So i created a diagram using the default `Drell-Yan` pattern available on the website, and compiled it by exporting to an image and everything worked (the export to png just runs the code in that overlay through pdflatex). Here is the diagram code that I was given by the export overlay:

```
\begin{feynman} 
    \fermion[label=$l$, labelDistance=-0.70, labelLocation=0.49]{2.20, 2.20}{0.20, 4.20}
    \fermion[label=$\anti{l}$, labelDistance=1.00, labelLocation=0.44]{0.20, 0.20}{2.20, 2.20}
    \electroweak[color=2d89d3, label=$Z$]{2.20, 2.20}{5.20, 2.20}
    \fermion[label=$l$]{7.20, 4.20}{5.20, 2.20}
    \fermion[label=$\anti{l}$]{5.20, 2.20}{7.20, 0.20}
\end{feynman}
```

All I did was drag the label on the upper left line below the propagator, can you give this a try and make sure  you see that the image generated puts the label in the right place? If so, I think the `.sty` download link might be pointing to an out of date version.

**Comment by AlecAivazis** [comment]
After playing around with this for a bit, it seems the error is in the negative label distance and a gluon propagator. I'll try to figure out the source tomorrow and publish a fix ASAP

**Comment by AlecAivazis** [comment]
@ExarchD this problem should be fixed now, can you verify?

**Comment by shwinnn** [comment]
Hi, I actually am still getting the same error with negative label locations. Parentheses don't solve the problem. As a minimal example:

`\fermion[label=$d$, labelDistance=-0.10, labelLocation=0.35]{0.20, 10.20}{1.40, 10.20}`

compiles but

`\fermion[label=$d$, labelDistance=-0.10, labelLocation=-0.35]{0.20, 10.20}{1.40, 10.20}`

doesn't. Parentheses don't seem to help.

**Comment by AlecAivazis** [comment]
@shwinnn i'm sorry to hear you're running into that. I just reproduced the problem but it might take me awhile to find the time to fix this. Until I do, you should be able to use a floating text element to put the label where you want

**Comment by shwinnn** [comment]
A label location of 0 works fine for my diagrams anyway! Thanks for the great tool.

**Comment by AlecAivazis** [comment]
@shwinnn - this should be fixed now

**Comment by mvaculciak** [comment]
Hi, 
first of all thanks for this lovely tool.

Unfortunately, this (error when setting negative labelLocation) is still an issue, but following the discussion https://tex.stackexchange.com/questions/460522/using-fp-package-to-compute-sum-breaks-fp-error-upn-stack-is-empty
I managed to fix it by adding "0+" to line 588 of feynman.sty.
            \FPeval{labelX}{\@temp@locX}  --> \FPeval{labelX}{0+\@temp@locX}

Hope it helps.
